// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using webSITE.Repositori.Data;

#nullable disable

namespace webSITE.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("webSITE.Models.Mahasiswa", b =>
                {
                    b.Property<string>("Nim")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("JenisKelamin")
                        .HasColumnType("int");

                    b.Property<string>("NamaLengkap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NamaPanggilan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TanggalLahir")
                        .HasColumnType("datetime2");

                    b.HasKey("Nim");

                    b.ToTable("TblMahasiswa");

                    b.HasData(
                        new
                        {
                            Nim = "2206080051",
                            Email = "aditaklal@gmail.com",
                            JenisKelamin = 0,
                            NamaLengkap = "Adi Juanito Taklal",
                            NamaPanggilan = "Adi",
                            Password = "adiairnona",
                            PhotoPath = "/img/contoh.jpeg",
                            TanggalLahir = new DateTime(2004, 2, 29, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Nim = "2206080052",
                            Email = "aditaklal@gmail.com",
                            JenisKelamin = 0,
                            NamaLengkap = "Adi Juanito Taklal",
                            NamaPanggilan = "Adi",
                            Password = "adiairnona",
                            PhotoPath = "/img/contoh.jpeg",
                            TanggalLahir = new DateTime(2004, 2, 29, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Nim = "2206080053",
                            Email = "aditaklal@gmail.com",
                            JenisKelamin = 0,
                            NamaLengkap = "Adi Juanito Taklal",
                            NamaPanggilan = "Adi",
                            Password = "adiairnona",
                            PhotoPath = "/img/contoh.jpeg",
                            TanggalLahir = new DateTime(2004, 2, 29, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Nim = "2206080054",
                            Email = "aditaklal@gmail.com",
                            JenisKelamin = 0,
                            NamaLengkap = "Adi Juanito Taklal",
                            NamaPanggilan = "Adi",
                            Password = "adiairnona",
                            PhotoPath = "/img/contoh.jpeg",
                            TanggalLahir = new DateTime(2004, 2, 29, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Nim = "2206080055",
                            Email = "aditaklal@gmail.com",
                            JenisKelamin = 0,
                            NamaLengkap = "Adi Juanito Taklal",
                            NamaPanggilan = "Adi",
                            Password = "adiairnona",
                            PhotoPath = "/img/contoh.jpeg",
                            TanggalLahir = new DateTime(2004, 2, 29, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Nim = "2206080056",
                            Email = "aditaklal@gmail.com",
                            JenisKelamin = 0,
                            NamaLengkap = "Adi Juanito Taklal",
                            NamaPanggilan = "Adi",
                            Password = "adiairnona",
                            PhotoPath = "/img/contoh.jpeg",
                            TanggalLahir = new DateTime(2004, 2, 29, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Nim = "2206080057",
                            Email = "aditaklal@gmail.com",
                            JenisKelamin = 0,
                            NamaLengkap = "Adi Juanito Taklal",
                            NamaPanggilan = "Adi",
                            Password = "adiairnona",
                            PhotoPath = "/img/contoh.jpeg",
                            TanggalLahir = new DateTime(2004, 2, 29, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Nim = "2206080058",
                            Email = "aditaklal@gmail.com",
                            JenisKelamin = 0,
                            NamaLengkap = "Adi Juanito Taklal",
                            NamaPanggilan = "Adi",
                            Password = "adiairnona",
                            PhotoPath = "/img/contoh.jpeg",
                            TanggalLahir = new DateTime(2004, 2, 29, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
