// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using webSITE.Repositori.Data;

#nullable disable

namespace webSITE.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("webSITE.Models.Foto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("IdKegiatan")
                        .HasColumnType("int");

                    b.Property<string>("PhotoPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Tanggal")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IdKegiatan");

                    b.ToTable("TblFoto");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IdKegiatan = 1,
                            PhotoPath = "/img/contoh.jpeg",
                            Tanggal = new DateTime(2023, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            IdKegiatan = 1,
                            PhotoPath = "/img/contoh.jpeg",
                            Tanggal = new DateTime(2023, 12, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            IdKegiatan = 1,
                            PhotoPath = "/img/contoh.jpeg",
                            Tanggal = new DateTime(2023, 12, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            IdKegiatan = 1,
                            PhotoPath = "/img/contoh.jpeg",
                            Tanggal = new DateTime(2023, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            IdKegiatan = 1,
                            PhotoPath = "/img/contoh.jpeg",
                            Tanggal = new DateTime(2023, 12, 6, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("webSITE.Models.Identity.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("IdMahasiswa")
                        .HasColumnType("int");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdMahasiswa")
                        .IsUnique();

                    b.ToTable("AppUser");
                });

            modelBuilder.Entity("webSITE.Models.Kegiatan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Keterangan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NamaKegiatan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TanggalBerakhir")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TanggalMulai")
                        .HasColumnType("datetime2");

                    b.Property<string>("TempatKegiatan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TblKegiatan");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Keterangan = "Kegiatan Pertama",
                            NamaKegiatan = "Kegiatan 1",
                            TanggalBerakhir = new DateTime(2023, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TanggalMulai = new DateTime(2023, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TempatKegiatan = "Undana"
                        });
                });

            modelBuilder.Entity("webSITE.Models.Mahasiswa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("JenisKelamin")
                        .HasColumnType("int");

                    b.Property<string>("NamaLengkap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NamaPanggilan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TanggalLahir")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("TblMahasiswa");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            JenisKelamin = 0,
                            NamaLengkap = "Adi Juanito Taklal",
                            NamaPanggilan = "Adi",
                            Nim = "2206080051",
                            PhotoPath = "/img/contoh.jpeg",
                            TanggalLahir = new DateTime(2004, 2, 29, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            JenisKelamin = 0,
                            NamaLengkap = "Adi Juanito Taklal",
                            NamaPanggilan = "Adi",
                            Nim = "2206080052",
                            PhotoPath = "/img/contoh.jpeg",
                            TanggalLahir = new DateTime(2004, 2, 29, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            JenisKelamin = 0,
                            NamaLengkap = "Adi Juanito Taklal",
                            NamaPanggilan = "Adi",
                            Nim = "2206080053",
                            PhotoPath = "/img/contoh.jpeg",
                            TanggalLahir = new DateTime(2004, 2, 29, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            JenisKelamin = 0,
                            NamaLengkap = "Adi Juanito Taklal",
                            NamaPanggilan = "Adi",
                            Nim = "2206080054",
                            PhotoPath = "/img/contoh.jpeg",
                            TanggalLahir = new DateTime(2004, 2, 29, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            JenisKelamin = 0,
                            NamaLengkap = "Adi Juanito Taklal",
                            NamaPanggilan = "Adi",
                            Nim = "2206080055",
                            PhotoPath = "/img/contoh.jpeg",
                            TanggalLahir = new DateTime(2004, 2, 29, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            JenisKelamin = 0,
                            NamaLengkap = "Adi Juanito Taklal",
                            NamaPanggilan = "Adi",
                            Nim = "2206080056",
                            PhotoPath = "/img/contoh.jpeg",
                            TanggalLahir = new DateTime(2004, 2, 29, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            JenisKelamin = 0,
                            NamaLengkap = "Adi Juanito Taklal",
                            NamaPanggilan = "Adi",
                            Nim = "2206080057",
                            PhotoPath = "/img/contoh.jpeg",
                            TanggalLahir = new DateTime(2004, 2, 29, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            JenisKelamin = 0,
                            NamaLengkap = "Adi Juanito Taklal",
                            NamaPanggilan = "Adi",
                            Nim = "2206080058",
                            PhotoPath = "/img/contoh.jpeg",
                            TanggalLahir = new DateTime(2004, 2, 29, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("webSITE.Models.MahasiswaFoto", b =>
                {
                    b.Property<int>("IdFoto")
                        .HasColumnType("int");

                    b.Property<int>("IdMahasiswa")
                        .HasColumnType("int");

                    b.HasKey("IdFoto", "IdMahasiswa");

                    b.HasIndex("IdMahasiswa");

                    b.ToTable("TblMahasiswaFoto");

                    b.HasData(
                        new
                        {
                            IdFoto = 1,
                            IdMahasiswa = 1
                        },
                        new
                        {
                            IdFoto = 1,
                            IdMahasiswa = 2
                        },
                        new
                        {
                            IdFoto = 2,
                            IdMahasiswa = 1
                        },
                        new
                        {
                            IdFoto = 2,
                            IdMahasiswa = 2
                        },
                        new
                        {
                            IdFoto = 3,
                            IdMahasiswa = 1
                        },
                        new
                        {
                            IdFoto = 3,
                            IdMahasiswa = 2
                        },
                        new
                        {
                            IdFoto = 4,
                            IdMahasiswa = 1
                        },
                        new
                        {
                            IdFoto = 4,
                            IdMahasiswa = 2
                        },
                        new
                        {
                            IdFoto = 5,
                            IdMahasiswa = 1
                        },
                        new
                        {
                            IdFoto = 5,
                            IdMahasiswa = 2
                        });
                });

            modelBuilder.Entity("webSITE.Models.PesertaKegiatan", b =>
                {
                    b.Property<int>("IdKegiatan")
                        .HasColumnType("int");

                    b.Property<int>("IdMahasiswa")
                        .HasColumnType("int");

                    b.HasKey("IdKegiatan", "IdMahasiswa");

                    b.HasIndex("IdMahasiswa");

                    b.ToTable("TblPesertaKegiatan");

                    b.HasData(
                        new
                        {
                            IdKegiatan = 1,
                            IdMahasiswa = 1
                        },
                        new
                        {
                            IdKegiatan = 1,
                            IdMahasiswa = 2
                        });
                });

            modelBuilder.Entity("webSITE.Models.Foto", b =>
                {
                    b.HasOne("webSITE.Models.Kegiatan", "Kegiatan")
                        .WithMany("DaftarFoto")
                        .HasForeignKey("IdKegiatan");

                    b.Navigation("Kegiatan");
                });

            modelBuilder.Entity("webSITE.Models.Identity.AppUser", b =>
                {
                    b.HasOne("webSITE.Models.Mahasiswa", "Mahasiswa")
                        .WithOne("AppUser")
                        .HasForeignKey("webSITE.Models.Identity.AppUser", "IdMahasiswa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mahasiswa");
                });

            modelBuilder.Entity("webSITE.Models.MahasiswaFoto", b =>
                {
                    b.HasOne("webSITE.Models.Foto", null)
                        .WithMany()
                        .HasForeignKey("IdFoto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("webSITE.Models.Mahasiswa", null)
                        .WithMany()
                        .HasForeignKey("IdMahasiswa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("webSITE.Models.PesertaKegiatan", b =>
                {
                    b.HasOne("webSITE.Models.Kegiatan", null)
                        .WithMany()
                        .HasForeignKey("IdKegiatan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("webSITE.Models.Mahasiswa", null)
                        .WithMany()
                        .HasForeignKey("IdMahasiswa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("webSITE.Models.Kegiatan", b =>
                {
                    b.Navigation("DaftarFoto");
                });

            modelBuilder.Entity("webSITE.Models.Mahasiswa", b =>
                {
                    b.Navigation("AppUser");
                });
#pragma warning restore 612, 618
        }
    }
}
